export enum pokemonTypes {
  FETCH_POKEMON_REQUEST = "FETCH_POKEMON_REQUEST",
  FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS",
  FETCH_POKEMON_FAILURE = "FETCH_POKEMON_FAILURE",
  FETCH_ONE_POKEMON_SUCCESS = "FETCH_ONE_POKEMON_SUCCESS",
  FETCH_ONE_POKEMON_FAILURE = "FETCH_ONE_POKEMON_FAILURE",
  FETCH_ONE_POKEMON_REQUEST = "FETCH_ONE_POKEMON_REQUEST"
}
